#include "keycode.h"

static int sc_to_key_map[128] = {
    [SCANCODE_ESC] = KEYCODE_ESC,
    [SCANCODE_1] = KEYCODE_1,
    [SCANCODE_2] = KEYCODE_2,
    [SCANCODE_3] = KEYCODE_3,
    [SCANCODE_4] = KEYCODE_4,
    [SCANCODE_5] = KEYCODE_5,
    [SCANCODE_6] = KEYCODE_6,
    [SCANCODE_7] = KEYCODE_7,
    [SCANCODE_8] = KEYCODE_8,
    [SCANCODE_9] = KEYCODE_9,
    [SCANCODE_0] = KEYCODE_0,
    [SCANCODE_MINUS] = KEYCODE_MINUS,
    [SCANCODE_EQUAL] = KEYCODE_EQUAL,
    [SCANCODE_BACKSPACE] = KEYCODE_BACKSPACE,
    [SCANCODE_TAB] = KEYCODE_TAB,
    [SCANCODE_Q] = KEYCODE_Q,
    [SCANCODE_W] = KEYCODE_W,
    [SCANCODE_E] = KEYCODE_E,
    [SCANCODE_R] = KEYCODE_R,
    [SCANCODE_T] = KEYCODE_T,
    [SCANCODE_Y] = KEYCODE_Y,
    [SCANCODE_U] = KEYCODE_U,
    [SCANCODE_I] = KEYCODE_I,
    [SCANCODE_O] = KEYCODE_O,
    [SCANCODE_P] = KEYCODE_P,
    [SCANCODE_LEFTBRACE] = KEYCODE_LEFTBRACE,
    [SCANCODE_RIGHTBRACE] = KEYCODE_RIGHTBRACE,
    [SCANCODE_ENTER] = KEYCODE_ENTER,
    [SCANCODE_LEFTCTRL] = KEYCODE_LEFTCTRL,
    [SCANCODE_A] = KEYCODE_A,
    [SCANCODE_S] = KEYCODE_S,
    [SCANCODE_D] = KEYCODE_D,
    [SCANCODE_F] = KEYCODE_F,
    [SCANCODE_G] = KEYCODE_G,
    [SCANCODE_H] = KEYCODE_H,
    [SCANCODE_J] = KEYCODE_J,
    [SCANCODE_K] = KEYCODE_K,
    [SCANCODE_L] = KEYCODE_L,
    [SCANCODE_SEMICOLON] = KEYCODE_SEMICOLON,
    [SCANCODE_APOSTROPHE] = KEYCODE_APOSTROPHE,
    [SCANCODE_GRAVE] = KEYCODE_GRAVE,
    [SCANCODE_LEFTSHIFT] = KEYCODE_LEFTSHIFT,
    [SCANCODE_BACKSLASH] = KEYCODE_BACKSLASH,
    [SCANCODE_Z] = KEYCODE_Z,
    [SCANCODE_X] = KEYCODE_X,
    [SCANCODE_C] = KEYCODE_C,
    [SCANCODE_V] = KEYCODE_V,
    [SCANCODE_B] = KEYCODE_B,
    [SCANCODE_N] = KEYCODE_N,
    [SCANCODE_M] = KEYCODE_M,
    [SCANCODE_COMMA] = KEYCODE_COMMA,
    [SCANCODE_DOT] = KEYCODE_DOT,
    [SCANCODE_SLASH] = KEYCODE_SLASH,
    [SCANCODE_RIGHTSHIFT] = KEYCODE_RIGHTSHIFT,
    [SCANCODE_LEFTALT] = KEYCODE_LEFTALT,
    [SCANCODE_SPACE] = KEYCODE_SPACE,
    [SCANCODE_CAPSLOCK] = KEYCODE_CAPSLOCK,
    [SCANCODE_F1] = KEYCODE_F1,
    [SCANCODE_F2] = KEYCODE_F2,
    [SCANCODE_F3] = KEYCODE_F3,
    [SCANCODE_F4] = KEYCODE_F4,
    [SCANCODE_F5] = KEYCODE_F5,
    [SCANCODE_F6] = KEYCODE_F6,
    [SCANCODE_F7] = KEYCODE_F7,
    [SCANCODE_F8] = KEYCODE_F8,
    [SCANCODE_F9] = KEYCODE_F9,
    [SCANCODE_F10] = KEYCODE_F10,
    [SCANCODE_F11] = KEYCODE_F11,
    [SCANCODE_F12] = KEYCODE_F12,
    // [SCANCODE_LEFTMETA] = KEYCODE_LEFTMETA,
    // [SCANCODE_RIGHTMETA] = KEYCODE_RIGHTMETA,
    // [SCANCODE_MENU] = KEYCODE_MENU,
    // [SCANCODE_RIGHTCTRL] = KEYCODE_RIGHTCTRL,
    // [SCANCODE_RIGHTALT] = KEYCODE_RIGHTALT,
    [SCANCODE_SYSRQ] = KEYCODE_SYSRQ,
    [SCANCODE_SCROLLLOCK] = KEYCODE_SCROLLLOCK,
    // [SCANCODE_PAUSE] = KEYCODE_PAUSE,
    // [SCANCODE_INSERT] = KEYCODE_INSERT,
    // [SCANCODE_DELETE] = KEYCODE_DELETE,
    // [SCANCODE_HOME] = KEYCODE_HOME,
    // [SCANCODE_END] = KEYCODE_END,
    // [SCANCODE_PAGEUP] = KEYCODE_PAGEUP,
    // [SCANCODE_PAGEDOWN] = KEYCODE_PAGEDOWN,
    // [SCANCODE_UP] = KEYCODE_UP,
    // [SCANCODE_LEFT] = KEYCODE_LEFT,
    // [SCANCODE_RIGHT] = KEYCODE_RIGHT,
    // [SCANCODE_DOWN] = KEYCODE_DOWN,
    // [SCANCODE_NUMLOCK] = KEYCODE_NUMLOCK,
    [SCANCODE_KPASTERISK] = KEYCODE_KPASTERISK,
    [SCANCODE_KP7] = KEYCODE_KP7,
    [SCANCODE_KP8] = KEYCODE_KP8,
    [SCANCODE_KP9] = KEYCODE_KP9,
    [SCANCODE_KPMINUS] = KEYCODE_KPMINUS,
    [SCANCODE_KP4] = KEYCODE_KP4,
    [SCANCODE_KP5] = KEYCODE_KP5,
    [SCANCODE_KP6] = KEYCODE_KP6,
    [SCANCODE_KPPLUS] = KEYCODE_KPPLUS,
    [SCANCODE_KP1] = KEYCODE_KP1,
    [SCANCODE_KP2] = KEYCODE_KP2,
    [SCANCODE_KP3] = KEYCODE_KP3,
    [SCANCODE_KP0] = KEYCODE_KP0,
    [SCANCODE_KPDOT] = KEYCODE_KPDOT,
    // [SCANCODE_KPSLASH] = KEYCODE_KPSLASH,
    // [SCANCODE_KPENTER] = KEYCODE_KPENTER,
};

static int key_to_sc_map[136] = {
    [KEYCODE_ESC] = SCANCODE_ESC,
    [KEYCODE_1] = SCANCODE_1,
    [KEYCODE_2] = SCANCODE_2,
    [KEYCODE_3] = SCANCODE_3,
    [KEYCODE_4] = SCANCODE_4,
    [KEYCODE_5] = SCANCODE_5,
    [KEYCODE_6] = SCANCODE_6,
    [KEYCODE_7] = SCANCODE_7,
    [KEYCODE_8] = SCANCODE_8,
    [KEYCODE_9] = SCANCODE_9,
    [KEYCODE_0] = SCANCODE_0,
    [KEYCODE_MINUS] = SCANCODE_MINUS,
    [KEYCODE_EQUAL] = SCANCODE_EQUAL,
    [KEYCODE_BACKSPACE] = SCANCODE_BACKSPACE,
    [KEYCODE_TAB] = SCANCODE_TAB,
    [KEYCODE_Q] = SCANCODE_Q,
    [KEYCODE_W] = SCANCODE_W,
    [KEYCODE_E] = SCANCODE_E,
    [KEYCODE_R] = SCANCODE_R,
    [KEYCODE_T] = SCANCODE_T,
    [KEYCODE_Y] = SCANCODE_Y,
    [KEYCODE_U] = SCANCODE_U,
    [KEYCODE_I] = SCANCODE_I,
    [KEYCODE_O] = SCANCODE_O,
    [KEYCODE_P] = SCANCODE_P,
    [KEYCODE_LEFTBRACE] = SCANCODE_LEFTBRACE,
    [KEYCODE_RIGHTBRACE] = SCANCODE_RIGHTBRACE,
    [KEYCODE_ENTER] = SCANCODE_ENTER,
    [KEYCODE_LEFTCTRL] = SCANCODE_LEFTCTRL,
    [KEYCODE_A] = SCANCODE_A,
    [KEYCODE_S] = SCANCODE_S,
    [KEYCODE_D] = SCANCODE_D,
    [KEYCODE_F] = SCANCODE_F,
    [KEYCODE_G] = SCANCODE_G,
    [KEYCODE_H] = SCANCODE_H,
    [KEYCODE_J] = SCANCODE_J,
    [KEYCODE_K] = SCANCODE_K,
    [KEYCODE_L] = SCANCODE_L,
    [KEYCODE_SEMICOLON] = SCANCODE_SEMICOLON,
    [KEYCODE_APOSTROPHE] = SCANCODE_APOSTROPHE,
    [KEYCODE_GRAVE] = SCANCODE_GRAVE,
    [KEYCODE_LEFTSHIFT] = SCANCODE_LEFTSHIFT,
    [KEYCODE_BACKSLASH] = SCANCODE_BACKSLASH,
    [KEYCODE_Z] = SCANCODE_Z,
    [KEYCODE_X] = SCANCODE_X,
    [KEYCODE_C] = SCANCODE_C,
    [KEYCODE_V] = SCANCODE_V,
    [KEYCODE_B] = SCANCODE_B,
    [KEYCODE_N] = SCANCODE_N,
    [KEYCODE_M] = SCANCODE_M,
    [KEYCODE_COMMA] = SCANCODE_COMMA,
    [KEYCODE_DOT] = SCANCODE_DOT,
    [KEYCODE_SLASH] = SCANCODE_SLASH,
    [KEYCODE_RIGHTSHIFT] = SCANCODE_RIGHTSHIFT,
    [KEYCODE_LEFTALT] = SCANCODE_LEFTALT,
    [KEYCODE_SPACE] = SCANCODE_SPACE,
    [KEYCODE_CAPSLOCK] = SCANCODE_CAPSLOCK,
    [KEYCODE_F1] = SCANCODE_F1,
    [KEYCODE_F2] = SCANCODE_F2,
    [KEYCODE_F3] = SCANCODE_F3,
    [KEYCODE_F4] = SCANCODE_F4,
    [KEYCODE_F5] = SCANCODE_F5,
    [KEYCODE_F6] = SCANCODE_F6,
    [KEYCODE_F7] = SCANCODE_F7,
    [KEYCODE_F8] = SCANCODE_F8,
    [KEYCODE_F9] = SCANCODE_F9,
    [KEYCODE_F10] = SCANCODE_F10,
    [KEYCODE_F11] = SCANCODE_F11,
    [KEYCODE_F12] = SCANCODE_F12,
    [KEYCODE_LEFTMETA] = SCANCODE_LEFTMETA,
    [KEYCODE_RIGHTMETA] = SCANCODE_RIGHTMETA,
    [KEYCODE_MENU] = SCANCODE_MENU,
    [KEYCODE_RIGHTCTRL] = SCANCODE_RIGHTCTRL,
    [KEYCODE_RIGHTALT] = SCANCODE_RIGHTALT,
    [KEYCODE_SYSRQ] = SCANCODE_SYSRQ,
    [KEYCODE_SCROLLLOCK] = SCANCODE_SCROLLLOCK,
    [KEYCODE_PAUSE] = SCANCODE_PAUSE,
    [KEYCODE_INSERT] = SCANCODE_INSERT,
    [KEYCODE_DELETE] = SCANCODE_DELETE,
    [KEYCODE_HOME] = SCANCODE_HOME,
    [KEYCODE_END] = SCANCODE_END,
    [KEYCODE_PAGEUP] = SCANCODE_PAGEUP,
    [KEYCODE_PAGEDOWN] = SCANCODE_PAGEDOWN,
    [KEYCODE_UP] = SCANCODE_UP,
    [KEYCODE_LEFT] = SCANCODE_LEFT,
    [KEYCODE_RIGHT] = SCANCODE_RIGHT,
    [KEYCODE_DOWN] = SCANCODE_DOWN,
    [KEYCODE_NUMLOCK] = SCANCODE_NUMLOCK,
    [KEYCODE_KPASTERISK] = SCANCODE_KPASTERISK,
    [KEYCODE_KP7] = SCANCODE_KP7,
    [KEYCODE_KP8] = SCANCODE_KP8,
    [KEYCODE_KP9] = SCANCODE_KP9,
    [KEYCODE_KPMINUS] = SCANCODE_KPMINUS,
    [KEYCODE_KP4] = SCANCODE_KP4,
    [KEYCODE_KP5] = SCANCODE_KP5,
    [KEYCODE_KP6] = SCANCODE_KP6,
    [KEYCODE_KPPLUS] = SCANCODE_KPPLUS,
    [KEYCODE_KP1] = SCANCODE_KP1,
    [KEYCODE_KP2] = SCANCODE_KP2,
    [KEYCODE_KP3] = SCANCODE_KP3,
    [KEYCODE_KP0] = SCANCODE_KP0,
    [KEYCODE_KPDOT] = SCANCODE_KPDOT,
    [KEYCODE_KPSLASH] = SCANCODE_KPSLASH,
    [KEYCODE_KPENTER] = SCANCODE_KPENTER,
};

DLL_EXPORT int scancode_to_keycode(int scancode)
{
  if (SCANCODE_LEFTMETA == scancode)
    return KEYCODE_LEFTMETA; // 0xe05b
  if (SCANCODE_RIGHTMETA == scancode)
    return KEYCODE_RIGHTMETA; // 0xe05c
  if (SCANCODE_MENU == scancode)
    return KEYCODE_MENU; // 0xe05d
  if (SCANCODE_RIGHTCTRL == scancode)
    return KEYCODE_RIGHTCTRL; // 0xe01d
  if (SCANCODE_RIGHTALT == scancode)
    return KEYCODE_RIGHTALT; // 0xe038
  if (SCANCODE_KPSLASH == scancode)
    return KEYCODE_KPSLASH; // 0xe035
  if (SCANCODE_PAUSE == scancode)
    return KEYCODE_PAUSE; // 0xe11d
  if (SCANCODE_INSERT == scancode)
    return KEYCODE_INSERT; // 0xe052
  if (SCANCODE_DELETE == scancode)
    return KEYCODE_DELETE; // 0xe053
  if (SCANCODE_HOME == scancode)
    return KEYCODE_HOME; // 0xe047
  if (SCANCODE_END == scancode)
    return KEYCODE_END; // 0xe04f
  if (SCANCODE_PAGEUP == scancode)
    return KEYCODE_PAGEUP; // 0xe049
  if (SCANCODE_PAGEDOWN == scancode)
    return KEYCODE_PAGEDOWN; // 0xe051
  if (SCANCODE_UP == scancode)
    return KEYCODE_UP; // 0xe048
  if (SCANCODE_LEFT == scancode)
    return KEYCODE_LEFT; // 0xe046
  if (SCANCODE_RIGHT == scancode)
    return KEYCODE_RIGHT; // 0xe04d
  if (SCANCODE_DOWN == scancode)
    return KEYCODE_DOWN; // 0xe050
  if (SCANCODE_KPENTER == scancode)
    return KEYCODE_KPENTER; // 0xe01c
  if (SCANCODE_NUMLOCK == scancode)
    return KEYCODE_NUMLOCK; // 0xe045

  // printf("scancode=%d keycode=%d\n", scancode, sc_to_key_map[scancode]);
  return sc_to_key_map[scancode];
}

DLL_EXPORT int keycode_to_scancode(int keycode)
{
  return key_to_sc_map[keycode];
}