#include "keycode.h"

static int sc_to_key_map[128] = {
    [SCANCODE_ESC] = KEY_ESC,
    [SCANCODE_1] = KEY_1,
    [SCANCODE_2] = KEY_2,
    [SCANCODE_3] = KEY_3,
    [SCANCODE_4] = KEY_4,
    [SCANCODE_5] = KEY_5,
    [SCANCODE_6] = KEY_6,
    [SCANCODE_7] = KEY_7,
    [SCANCODE_8] = KEY_8,
    [SCANCODE_9] = KEY_9,
    [SCANCODE_0] = KEY_0,
    [SCANCODE_MINUS] = KEY_MINUS,
    [SCANCODE_EQUAL] = KEY_EQUAL,
    [SCANCODE_BACKSPACE] = KEY_BACKSPACE,
    [SCANCODE_TAB] = KEY_TAB,
    [SCANCODE_Q] = KEY_Q,
    [SCANCODE_W] = KEY_W,
    [SCANCODE_E] = KEY_E,
    [SCANCODE_R] = KEY_R,
    [SCANCODE_T] = KEY_T,
    [SCANCODE_Y] = KEY_Y,
    [SCANCODE_U] = KEY_U,
    [SCANCODE_I] = KEY_I,
    [SCANCODE_O] = KEY_O,
    [SCANCODE_P] = KEY_P,
    [SCANCODE_LEFTBRACE] = KEY_LEFTBRACE,
    [SCANCODE_RIGHTBRACE] = KEY_RIGHTBRACE,
    [SCANCODE_ENTER] = KEY_ENTER,
    [SCANCODE_LEFTCTRL] = KEY_LEFTCTRL,
    [SCANCODE_A] = KEY_A,
    [SCANCODE_S] = KEY_S,
    [SCANCODE_D] = KEY_D,
    [SCANCODE_F] = KEY_F,
    [SCANCODE_G] = KEY_G,
    [SCANCODE_H] = KEY_H,
    [SCANCODE_J] = KEY_J,
    [SCANCODE_K] = KEY_K,
    [SCANCODE_L] = KEY_L,
    [SCANCODE_SEMICOLON] = KEY_SEMICOLON,
    [SCANCODE_APOSTROPHE] = KEY_APOSTROPHE,
    [SCANCODE_GRAVE] = KEY_GRAVE,
    [SCANCODE_LEFTSHIFT] = KEY_LEFTSHIFT,
    [SCANCODE_BACKSLASH] = KEY_BACKSLASH,
    [SCANCODE_Z] = KEY_Z,
    [SCANCODE_X] = KEY_X,
    [SCANCODE_C] = KEY_C,
    [SCANCODE_V] = KEY_V,
    [SCANCODE_B] = KEY_B,
    [SCANCODE_N] = KEY_N,
    [SCANCODE_M] = KEY_M,
    [SCANCODE_COMMA] = KEY_COMMA,
    [SCANCODE_DOT] = KEY_DOT,
    [SCANCODE_SLASH] = KEY_SLASH,
    [SCANCODE_RIGHTSHIFT] = KEY_RIGHTSHIFT,
    [SCANCODE_LEFTALT] = KEY_LEFTALT,
    [SCANCODE_SPACE] = KEY_SPACE,
    [SCANCODE_CAPSLOCK] = KEY_CAPSLOCK,
    [SCANCODE_F1] = KEY_F1,
    [SCANCODE_F2] = KEY_F2,
    [SCANCODE_F3] = KEY_F3,
    [SCANCODE_F4] = KEY_F4,
    [SCANCODE_F5] = KEY_F5,
    [SCANCODE_F6] = KEY_F6,
    [SCANCODE_F7] = KEY_F7,
    [SCANCODE_F8] = KEY_F8,
    [SCANCODE_F9] = KEY_F9,
    [SCANCODE_F10] = KEY_F10,
    [SCANCODE_F11] = KEY_F11,
    [SCANCODE_F12] = KEY_F12,
    // [SCANCODE_LEFTMETA] = KEY_LEFTMETA,
    // [SCANCODE_RIGHTMETA] = KEY_RIGHTMETA,
    // [SCANCODE_MENU] = KEY_MENU,
    // [SCANCODE_RIGHTCTRL] = KEY_RIGHTCTRL,
    // [SCANCODE_RIGHTALT] = KEY_RIGHTALT,
    [SCANCODE_SYSRQ] = KEY_SYSRQ,
    [SCANCODE_SCROLLLOCK] = KEY_SCROLLLOCK,
    // [SCANCODE_PAUSE] = KEY_PAUSE,
    // [SCANCODE_INSERT] = KEY_INSERT,
    // [SCANCODE_DELETE] = KEY_DELETE,
    // [SCANCODE_HOME] = KEY_HOME,
    // [SCANCODE_END] = KEY_END,
    // [SCANCODE_PAGEUP] = KEY_PAGEUP,
    // [SCANCODE_PAGEDOWN] = KEY_PAGEDOWN,
    // [SCANCODE_UP] = KEY_UP,
    // [SCANCODE_LEFT] = KEY_LEFT,
    // [SCANCODE_RIGHT] = KEY_RIGHT,
    // [SCANCODE_DOWN] = KEY_DOWN,
    // [SCANCODE_NUMLOCK] = KEY_NUMLOCK,
    [SCANCODE_KPASTERISK] = KEY_KPASTERISK,
    [SCANCODE_KP7] = KEY_KP7,
    [SCANCODE_KP8] = KEY_KP8,
    [SCANCODE_KP9] = KEY_KP9,
    [SCANCODE_KPMINUS] = KEY_KPMINUS,
    [SCANCODE_KP4] = KEY_KP4,
    [SCANCODE_KP5] = KEY_KP5,
    [SCANCODE_KP6] = KEY_KP6,
    [SCANCODE_KPPLUS] = KEY_KPPLUS,
    [SCANCODE_KP1] = KEY_KP1,
    [SCANCODE_KP2] = KEY_KP2,
    [SCANCODE_KP3] = KEY_KP3,
    [SCANCODE_KP0] = KEY_KP0,
    [SCANCODE_KPDOT] = KEY_KPDOT,
    // [SCANCODE_KPSLASH] = KEY_KPSLASH,
    // [SCANCODE_KPENTER] = KEY_KPENTER,
};

static int key_to_sc_map[136] = {
    [KEY_ESC] = SCANCODE_ESC,
    [KEY_1] = SCANCODE_1,
    [KEY_2] = SCANCODE_2,
    [KEY_3] = SCANCODE_3,
    [KEY_4] = SCANCODE_4,
    [KEY_5] = SCANCODE_5,
    [KEY_6] = SCANCODE_6,
    [KEY_7] = SCANCODE_7,
    [KEY_8] = SCANCODE_8,
    [KEY_9] = SCANCODE_9,
    [KEY_0] = SCANCODE_0,
    [KEY_MINUS] = SCANCODE_MINUS,
    [KEY_EQUAL] = SCANCODE_EQUAL,
    [KEY_BACKSPACE] = SCANCODE_BACKSPACE,
    [KEY_TAB] = SCANCODE_TAB,
    [KEY_Q] = SCANCODE_Q,
    [KEY_W] = SCANCODE_W,
    [KEY_E] = SCANCODE_E,
    [KEY_R] = SCANCODE_R,
    [KEY_T] = SCANCODE_T,
    [KEY_Y] = SCANCODE_Y,
    [KEY_U] = SCANCODE_U,
    [KEY_I] = SCANCODE_I,
    [KEY_O] = SCANCODE_O,
    [KEY_P] = SCANCODE_P,
    [KEY_LEFTBRACE] = SCANCODE_LEFTBRACE,
    [KEY_RIGHTBRACE] = SCANCODE_RIGHTBRACE,
    [KEY_ENTER] = SCANCODE_ENTER,
    [KEY_LEFTCTRL] = SCANCODE_LEFTCTRL,
    [KEY_A] = SCANCODE_A,
    [KEY_S] = SCANCODE_S,
    [KEY_D] = SCANCODE_D,
    [KEY_F] = SCANCODE_F,
    [KEY_G] = SCANCODE_G,
    [KEY_H] = SCANCODE_H,
    [KEY_J] = SCANCODE_J,
    [KEY_K] = SCANCODE_K,
    [KEY_L] = SCANCODE_L,
    [KEY_SEMICOLON] = SCANCODE_SEMICOLON,
    [KEY_APOSTROPHE] = SCANCODE_APOSTROPHE,
    [KEY_GRAVE] = SCANCODE_GRAVE,
    [KEY_LEFTSHIFT] = SCANCODE_LEFTSHIFT,
    [KEY_BACKSLASH] = SCANCODE_BACKSLASH,
    [KEY_Z] = SCANCODE_Z,
    [KEY_X] = SCANCODE_X,
    [KEY_C] = SCANCODE_C,
    [KEY_V] = SCANCODE_V,
    [KEY_B] = SCANCODE_B,
    [KEY_N] = SCANCODE_N,
    [KEY_M] = SCANCODE_M,
    [KEY_COMMA] = SCANCODE_COMMA,
    [KEY_DOT] = SCANCODE_DOT,
    [KEY_SLASH] = SCANCODE_SLASH,
    [KEY_RIGHTSHIFT] = SCANCODE_RIGHTSHIFT,
    [KEY_LEFTALT] = SCANCODE_LEFTALT,
    [KEY_SPACE] = SCANCODE_SPACE,
    [KEY_CAPSLOCK] = SCANCODE_CAPSLOCK,
    [KEY_F1] = SCANCODE_F1,
    [KEY_F2] = SCANCODE_F2,
    [KEY_F3] = SCANCODE_F3,
    [KEY_F4] = SCANCODE_F4,
    [KEY_F5] = SCANCODE_F5,
    [KEY_F6] = SCANCODE_F6,
    [KEY_F7] = SCANCODE_F7,
    [KEY_F8] = SCANCODE_F8,
    [KEY_F9] = SCANCODE_F9,
    [KEY_F10] = SCANCODE_F10,
    [KEY_F11] = SCANCODE_F11,
    [KEY_F12] = SCANCODE_F12,
    [KEY_LEFTMETA] = SCANCODE_LEFTMETA,
    [KEY_RIGHTMETA] = SCANCODE_RIGHTMETA,
    [KEY_MENU] = SCANCODE_MENU,
    [KEY_RIGHTCTRL] = SCANCODE_RIGHTCTRL,
    [KEY_RIGHTALT] = SCANCODE_RIGHTALT,
    [KEY_SYSRQ] = SCANCODE_SYSRQ,
    [KEY_SCROLLLOCK] = SCANCODE_SCROLLLOCK,
    [KEY_PAUSE] = SCANCODE_PAUSE,
    [KEY_INSERT] = SCANCODE_INSERT,
    [KEY_DELETE] = SCANCODE_DELETE,
    [KEY_HOME] = SCANCODE_HOME,
    [KEY_END] = SCANCODE_END,
    [KEY_PAGEUP] = SCANCODE_PAGEUP,
    [KEY_PAGEDOWN] = SCANCODE_PAGEDOWN,
    [KEY_UP] = SCANCODE_UP,
    [KEY_LEFT] = SCANCODE_LEFT,
    [KEY_RIGHT] = SCANCODE_RIGHT,
    [KEY_DOWN] = SCANCODE_DOWN,
    [KEY_NUMLOCK] = SCANCODE_NUMLOCK,
    [KEY_KPASTERISK] = SCANCODE_KPASTERISK,
    [KEY_KP7] = SCANCODE_KP7,
    [KEY_KP8] = SCANCODE_KP8,
    [KEY_KP9] = SCANCODE_KP9,
    [KEY_KPMINUS] = SCANCODE_KPMINUS,
    [KEY_KP4] = SCANCODE_KP4,
    [KEY_KP5] = SCANCODE_KP5,
    [KEY_KP6] = SCANCODE_KP6,
    [KEY_KPPLUS] = SCANCODE_KPPLUS,
    [KEY_KP1] = SCANCODE_KP1,
    [KEY_KP2] = SCANCODE_KP2,
    [KEY_KP3] = SCANCODE_KP3,
    [KEY_KP0] = SCANCODE_KP0,
    [KEY_KPDOT] = SCANCODE_KPDOT,
    [KEY_KPSLASH] = SCANCODE_KPSLASH,
    [KEY_KPENTER] = SCANCODE_KPENTER,
};

DLL_EXPORT int scancode_to_keycode(int scancode)
{
  if (SCANCODE_LEFTMETA == scancode)
    return KEY_LEFTMETA; // 0xe05b
  if (SCANCODE_RIGHTMETA == scancode)
    return KEY_RIGHTMETA; // 0xe05c
  if (SCANCODE_MENU == scancode)
    return KEY_MENU; // 0xe05d
  if (SCANCODE_RIGHTCTRL == scancode)
    return KEY_RIGHTCTRL; // 0xe01d
  if (SCANCODE_RIGHTALT == scancode)
    return KEY_RIGHTALT; // 0xe038
  if (SCANCODE_KPSLASH == scancode)
    return KEY_KPSLASH; // 0xe035
  if (SCANCODE_PAUSE == scancode)
    return KEY_PAUSE; // 0xe11d
  if (SCANCODE_INSERT == scancode)
    return KEY_INSERT; // 0xe052
  if (SCANCODE_DELETE == scancode)
    return KEY_DELETE; // 0xe053
  if (SCANCODE_HOME == scancode)
    return KEY_HOME; // 0xe047
  if (SCANCODE_END == scancode)
    return KEY_END; // 0xe04f
  if (SCANCODE_PAGEUP == scancode)
    return KEY_PAGEUP; // 0xe049
  if (SCANCODE_PAGEDOWN == scancode)
    return KEY_PAGEDOWN; // 0xe051
  if (SCANCODE_UP == scancode)
    return KEY_UP; // 0xe048
  if (SCANCODE_LEFT == scancode)
    return KEY_LEFT; // 0xe046
  if (SCANCODE_RIGHT == scancode)
    return KEY_RIGHT; // 0xe04d
  if (SCANCODE_DOWN == scancode)
    return KEY_DOWN; // 0xe050
  if (SCANCODE_KPENTER == scancode)
    return KEY_KPENTER; // 0xe01c
  if (SCANCODE_NUMLOCK == scancode)
    return KEY_NUMLOCK; // 0xe045

  printf("scancode=%d keycode=%d\n", scancode, sc_to_key_map[scancode]);
  return sc_to_key_map[scancode];
}

DLL_EXPORT int keycode_to_scancode(int keycode)
{
  return key_to_sc_map[keycode];
}